server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    username: postrges
    url: jdbc:postrgesql://localhost:5432/fraud
    password: inha-2020
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true